$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
display_name: product-reviews-gpt2
experiment_name: product-reviews-nlp
description: Fine tunning of the gpt2 model.
code: ../../src
command: >-
  jobtools train.py fine_tune \
    --train-path ${{inputs.train_path}}
    --test-path ${{inputs.test_path}}
    --baseline ${{inputs.baseline}}
inputs:
  train_path:
    path: azureml:product-reviews-train@latest
  eval_path:
    path: azureml:product-reviews-eval@latest
  baseline: 'gpt2'
environment:
  build:
    path: docker-context
compute: azureml:santiagxf-gpu-xl