name: finetuning_classifier_base
display_name: Finetune HuggingFace Classifier
version: 1
type: command
description: Finetune a HuggingFace Classifier.
tags: { category: HuggingFace, type: Classifier }
inputs:
  base_weights: 
    type: uri_folder
    description: The model checkpoint for weights initialization.
  base_tokenizer:
    type: uri_folder
    description: Pretrained tokenizer name or path if not from model_name.
  base_config: 
    type: uri_folder
    description: Pretrained GPT2 model configuration.
    optional: true
  train_path: 
    type: uri_folder
    description: Directory containing pre-processed training data.
  validation_path: 
    type: uri_folder
    description: Directory containing pre-processed validation data.
    optional: true
  text_column_name: 
    type: string
    description: Name of the column containing text.
    default: text
  label_column_name: 
    type: string
    description: Name of the column containing text.
    default: label
  num_labels: 
    type: integer
    description: Number of labels/classes in the target.
  batch_size: 
    type: integer
    description: Batch size per step on each device.
    default: 26
  num_train_epochs: 
    type: integer
    description: Number of training epochs.
    default: 20
  eval_strategy:
    type: string
    description: Evaluation strategy
    enum: ['epoch','steps','no']
outputs:
  weights:
    type: uri_folder
  tokenizer:
    type: uri_folder
  config:
    type: uri_folder
  model:
    type: uri_folder
code: .
environment: azureml:base-hf-transformer-trainer:1
command: >-
  jobtools finetune_classifier.py finetune 
    --weights-path ${{inputs.base_weights}} 
    --tokenizer-path ${{inputs.base_tokenizer}} 
    [--config-path ${{inputs.base_config}}] 
    --train-path ${{inputs.train_path}} 
    [--validation-path ${{inputs.validation_path}}] 
    --text-column-name ${{inputs.text_column_name}} 
    --label-column-name ${{inputs.label_column_name}} 
    --num-labels ${{inputs.num_labels}} 
    --batch-size ${{inputs.batch_size}} 
    --num-train-epochs ${{inputs.num_train_epochs}} 
    --eval-strategy ${{inputs.eval_strategy}}
    --ort False 
    --fp16 False 
    --deepspeed False 
    --model-output ${{outputs.model}} 
    --weights-output ${{outputs.weights}} 
    --tokenizer-output ${{outputs.tokenizer}} 
    --config-output ${{outputs.config}}